function peaks = houghpeaks(accum, numpeaks)
% HOUGHPEAKS finds peaks in the accumulation matrix, 'accum', generated by
% function HOUGHTF. The threshold for detecting peaks is 0.5*max(accum(:)).
% The number of peaks returned is at most 'numpeaks' and the default
% is 1 if 'numpeaks' is omitted.
%
% Copyright (c), Yuan-Liang Tang
% Associate Professor
% Department of Information Management
% Chaoyang University of Technology
% Taichung, Taiwan
% http://www.cyut.edu.tw/~yltang
% 
% Permission is hereby granted, free of charge, to any person obtaining
% a copy of this Software without restriction, subject to the following
% conditions:
% The above copyright notice and this permission notice should be included
% in all copies or substantial portions of the Software.
%
% The Software is provided "as is," without warranty of any kind.
%
% Created: May 3, 2010
%

if nargin==1
  numpeaks = 1;
elseif nargin~=2
  fprintf('Usage: peaks = houghpeaks(bw, <numpeaks>)\n');
  return;
end

% Reset the range of theta: -90~89 (function 'houghtf': -90~90)
accum = accum(:,1:end-1);

% Clear small line segments (less number of points)
thresh = 0.5*max(accum(:));
accum(accum<thresh) = 0;

% Non-maximal suppression
mask = fspecial('disk', 3)>0;
nbr = sum(mask(:));
highest = ordfilt2(accum, nbr, mask);
accum(highest~=accum) = 0;
[r c v] = find(accum);
peaks = [r c v];
peaks = sortrows(peaks, -3);

% Return at most 'numpeaks' peaks
peaks = peaks(1:min(numpeaks,end), 1:2);

